In [1]:
import numpy as np

# Section 1.1

In [2]:
# 57

A = np.array([[1, .5, .33, .25], 
              [.5, .33, .25, .21],
              [.33, .25, .2, .17],
              [.25, .2, .17, .14]])
B = np.array([1.1, 1.2, 1.3, 1.4]).reshape(4, 1)
X = np.linalg.solve(A, B)
print(X)

[[-15.]
 [ 40.]
 [ 45.]
 [-75.]]


In [3]:
# 59

A = np.array([[123.5, 61.3, -32.4], 
              [54.7, -45.6, 98.2],
              [42.4, -89.3, 12.9]])
B = np.array([-262.74, 197.4, 33.66]).reshape(3, 1)
X = np.linalg.solve(A, B)
print(X)

[[-1.2]
 [-0.6]
 [ 2.4]]


In [4]:
# 61 

A = np.array([[1/2, -3/7, 2/9], 
              [2/3, 4/9, -2/5],
              [4/5, -1/8, 4/3]])
B = np.array([349/630, -19/45, 139/150]).reshape(3, 1)
X = np.linalg.solve(A, B)
print(X)

[[ 0.2]
 [-0.8]
 [ 0.5]]


In [5]:
# 63

A = np.array([[1/8, -1/7, 1/6, -1/5], 
              [1/7, 1/6, -1/5, 1/4],
              [1/6, -1/5, 1/4, -1/3],
              [1/5, 1/4, -1/3, 1/2]])
B = np.array([1, 1, 1, 1]).reshape(4, 1)
X = np.linalg.solve(A, B)
print(X)

[[   6.88131073]
 [-163.31110688]
 [-210.29148409]
 [ -59.29129358]]


# Section 1.2

In [6]:
# 37.

A = np.array([[1, -2, 5, -3], 
              [1, 4, -7, -2],
              [3, -5, 7, 4]])
B = np.array([23.6, 45.7, 29.9]).reshape(3, 1)
# print(A)
# print(B)
# A_inv = np.linalg.inv(A)
# print(A_inv)
C = np.concatenate((A, B), axis=1)
print(C)
R0 = C[0, :]
R1 = C[1, :]
R2 = C[2, :]
R1 = R1 - R0
R2 = R2 - 3*R0
R2 = R2 - (1/6)*R1
R2 = R2/(-6)
R1 = R1/6 + 2*R2
R0 = R0 + 2*R1 -5*R2
R0 = R0.reshape(1, 5)
R1 = R1.reshape(1, 5)
R2 = R2.reshape(1, 5)
rref = np.concatenate((R0, R1, R2))
print(rref)

[[ 1.  -2.   5.  -3.  23.6]
 [ 1.   4.  -7.  -2.  45.7]
 [ 3.  -5.   7.   4.  29.9]]
[[ 1.          0.          0.         -0.52777778 23.53611111]
 [ 0.          1.          0.         -4.11111111 18.54444444]
 [-0.         -0.          1.         -2.13888889  7.43055556]]


In [7]:
# 39.

A = np.array([[1, -1, 2, 2, 6], 
              [3, -2, 4, 4, 12],
              [0, 1, -1, -1, -3],
              [2, -2, 4, 5, 15],
              [2, -2, 4, 4, 13]])
B = np.array([6, 14, -3, 10, 13]).reshape(5, 1)
X = np.linalg.solve(A, B)
print(X)

[[ 2.]
 [-2.]
 [ 3.]
 [-5.]
 [ 1.]]


In [8]:
# 41.

A = np.array([[4, -3, 1, -1, 2, -1], 
              [1, -2, 1, -3, 1, -4],
              [2, 1, -3, 1, -2, 5],
              [-2, 3, -1, 1, -1, 2],
              [1, -3, 1, -2, 1, -2],
              [5, -4, -1, -1, 4, 5]])
B = np.array([8, 4, 2, -7, 9, 9]).reshape(6, 1)
X = np.linalg.solve(A, B)
print(X)

[[ 1.]
 [-2.]
 [ 6.]
 [-3.]
 [-4.]
 [ 3.]]


# Section 2.3

In [24]:
# 29 
A = np.array([[1, 2, -1, 3, -1], 
              [1, -3, 1, 2, -1],
              [2, 1, 1, -3, 1],
              [1, -1, 2, 1, -1],
              [2, 1, -1, 2, 1]])
B = np.array([-3, -3, 6, 2, -3]).reshape(5, 1)
A_inv = np.linalg.inv(A)
# print(A.shape, B.shape, A_inv.shape)
print(np.dot(A_inv, B))
# Ans: (0, 1, 2, -1, 0)

(5, 5) (5, 1) (5, 5)
[[ 4.4408921e-16]
 [ 1.0000000e+00]
 [ 2.0000000e+00]
 [-1.0000000e+00]
 [-4.4408921e-16]]


In [25]:
# 31
A = np.array([[2, -3, 1, -2, 1, -4], 
              [3, 1, -4, 1, -1, 2],
              [4, 1, -3, 4, -1, 2],
              [-5, -1, 4, 2, -5, 3],
              [1, 1, -3, 4, -3, 1],
              [3, -1, 2, -3, 2, -6]])
B = np.array([20, -16, -12, -2, -15, 25]).reshape(6, 1)
A_inv = np.linalg.inv(A)
# print(A.shape, B.shape, A_inv.shape)
print(np.dot(A_inv, B))
# Ans: (1, -2, 3, 0, 1, -2)

(6, 6) (6, 1) (6, 6)
[[ 1.0000000e+00]
 [-2.0000000e+00]
 [ 3.0000000e+00]
 [ 4.4408921e-16]
 [ 1.0000000e+00]
 [-2.0000000e+00]]
